In [2]:
from pathlib import Path
import pandas as pd

In [3]:
# folder containing all sample TSVs
in_dir = Path("/home/dgohar/res/GenomeMatchinfo")
out_file = in_dir / "all_samples_combined.tsv"

In [3]:
# read all TSVs, add sample_id from filename, combine
dfs = []

for f in sorted(in_dir.glob("*.tsv")):
    if f.name == out_file.name:
        continue  # skip previous combined file if it exists
    
    sample_id = f.stem
    df = pd.read_csv(f, sep="\t")
    df.insert(0, "sample_id", sample_id)
    dfs.append(df)

combined = pd.concat(dfs, ignore_index=True)
combined.to_csv(out_file, sep="\t", index=False)

print(combined.shape)
combined.head()

(186, 26)

,sample_id,genome_id,taxid,tax_source,superkingdom,kingdom,domain_group,phylum,class,order,...,last_refinery_reads,seq_identity(%),genome_coverage(%),genome_ave_depth,read_depth(>1x),total_mapped_reads,bp_distribution_ratio,rel_abun_total,rel_abun_mapped,len_norm_abun
0,zr24632_17,GCA_000016765.1,392499.0,GenBank,NaN,Pseudomonadati,NaN,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,...,47702,93.3587,20.71,0.8348,4.8266,47702,0.7919,0.004736,0.004405,0.003378
1,zr24632_17,GCA_000381625.1,639034.0,GenBank,NaN,Pseudomonadati,NaN,Acidobacteriota,Terriglobia,Bryobacterales,...,22497,96.2610,13.23,0.3467,2.8884,22497,0.8580,0.002234,0.002077,0.001408
2,zr24632_17,GCA_000648925.1,1458357.0,GenBank,NaN,Pseudomonadati,NaN,Pseudomonadota,Betaproteobacteria,Burkholderiales,...,27342,93.2886,9.31,0.3818,5.0952,27342,0.7573,0.002715,0.002525,0.001330
3,zr24632_17,GCA_000824785.1,69974.0,GenBank,NaN,Pseudomonadati,NaN,Pseudomonadota,Alphaproteobacteria,Hyphomicrobiales,...,36894,94.3098,28.38,0.6866,3.0114,36894,0.7058,0.003663,0.003407,0.002165
4,zr24632_17,GCA_001647635.1,1575.0,GenBank,NaN,Bacillati,NaN,Actinomycetota,Actinomycetes,Micrococcales,...,33050,92.9072,27.55,1.0959,4.8798,33050,0.7676,0.003282,0.003052,0.003850

In [4]:
combined = pd.read_csv("res/GenomeMatchinfo/all_samples_combined.tsv", sep="\t")

In [5]:
# unique values
print("kingdom:")
print(sorted(combined["kingdom"].dropna().unique()))

print("\ndomain_group:")
print(sorted(combined["domain_group"].dropna().unique()))

kingdom:
['Bacillati', 'Fungi', 'Pseudomonadati', 'Thermotogati']

domain_group:
['Fungi']

In [6]:
combined["phylum"].value_counts(dropna=False).head(10)

phylum
Pseudomonadota     2319
Actinomycetota     1228
Ascomycota          162
Bacteroidota         97
Bacillota            91
Acidobacteriota      89
Gemmatimonadota      27
NaN                  26
Planctomycetota      17
Chloroflexota        12
Name: count, dtype: int64

In [7]:
bacterial_phyla = [
    "Pseudomonadota","Actinomycetota","Bacteroidota",
    "Bacillota","Acidobacteriota","Gemmatimonadota",
    "Planctomycetota","Chloroflexota"
]

combined.loc[combined["phylum"].isin(bacterial_phyla), "domain_group"] = "Bacteria"

In [8]:
combined["domain_group"].value_counts(dropna=False).head(10)

domain_group
Bacteria    3880
Fungi        172
NaN           49
Name: count, dtype: int64

In [12]:
combined.loc[
    combined["phylum"].isna(),
    ["genome_id", "sample_id", "full_lineage","rel_abun_mapped","rel_abun_total"]
]

,genome_id,sample_id,full_lineage,rel_abun_mapped,rel_abun_total
16,GCA_017308185.1,zr24632_17,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
136,GCF_021173085.1,zr24632_17,NaN,0.000000,0.000000
208,GCA_017308185.1,zr24632_18,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
377,GCF_021173085.1,zr24632_18,NaN,0.000000,0.000000
471,GCA_017308185.1,zr24632_19,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
659,GCF_021173085.1,zr24632_19,NaN,0.000000,0.000000
752,GCA_017308185.1,zr24632_20,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
935,GCF_021173085.1,zr24632_20,NaN,0.000000,0.000000
1229,GCF_021173085.1,zr24632_21,NaN,0.000000,0.000000
1330,GCF_963529995.1,zr24632_21,NaN,0.000000,0.000000
1538,GCF_021173085.1,zr24632_22,NaN,0.000000,0.000000
1806,GCF_021173085.1,zr24632_23,NaN,0.000000,0.000000
2089,GCF_021173085.1,zr24632_24,NaN,0.000000,0.000000
2180,GCA_017308185.1,zr24632_25,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
2289,GCF_021173085.1,zr24632_25,NaN,0.000000,0.000000
2351,GCA_017308185.1,zr24632_26,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
2509,GCF_021173085.1,zr24632_26,NaN,0.000000,0.000000
2582,GCA_017308185.1,zr24632_27,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
2753,GCF_021173085.1,zr24632_27,NaN,0.000000,0.000000
2824,GCA_017308185.1,zr24632_28,root [no rank]; cellular organisms [cellular r...,0.000000,0.000000
2996,GCF_021173085.1,zr24632_28,NaN,0.000000,0.000000
3180,GCF_001015195.1,zr24632_29,NaN,0.018035,0.009209
3371,GCF_040224145.1,zr24632_29,NaN,0.031173,0.015917
3402,GCF_963529995.1,zr24632_29,NaN,0.000000,0.000000
3656,GCF_963529995.1,zr24632_30,NaN,0.000000,0.000000
3933,GCF_963529995.1,zr24632_31,NaN,0.000000,0.000000

In [10]:
combined.columns

Index(['sample_id', 'genome_id', 'taxid', 'tax_source', 'superkingdom',
       'kingdom', 'domain_group', 'phylum', 'class', 'order', 'family',
       'genus', 'species', 'strain', 'full_lineage', 'sourmash_abun',
       'mapping_reads', 'filtered_mapped_reads', 'seq_identity(%)',
       'genome_coverage(%)', 'genome_ave_depth', 'read_depth(>1x)',
       'total_mapped_reads', 'bp_distribution_ratio', 'rel_abun_total',
       'rel_abun_mapped', 'len_norm_abun'],
      dtype='object')